# Generated by Django 4.2.7 on 2026-03-09 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_documentchunk'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='document',
            name='documents_uploade_d6a956_idx',
        ),
        migrations.RemoveField(
            model_name='document',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='processing_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='total_chunks',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='char_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='chunk_index',
            field=models.IntegerField(blank=True, default=0, help_text='Order of this chunk within the document', null=True),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='keywords',
            field=models.JSONField(blank=True, default=list, help_text='Auto-extracted keywords for this chunk', null=True),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='page_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='section_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='document',
            table='api_document',
        ),
    ]
